# This is a basic workflow to help you get started with Actions

name: blossom-ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the branch-0.2 branch
on:
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:      
      - name: Get pull request ref
        id: pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:issue_id
          repository: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ fromJson(steps.pull_request_ref.outputs.data).head.ref }}
          lfs: 'true'

      - name: set java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: get projects 2
        run: |
          echo ::set-env name=projects::$(mvn -am dependency:tree | grep maven-dependency-plugin | awk '{ out="com.nvidia:"$(NF-1);print out }' | grep rapids | xargs | sed -e 's/ /,/g')
      
      - name: Synopsys Detect
        uses: blackducksoftware/github-action@2.0.1
        env:
          PROJECTS: ${{ env.projects }}
        with:
          args: >
            --blackduck.url="${{ secrets.BLACKDUCK_URL}}" 
            --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" 
            --detect.force.success=false 
            --detect.maven.build.command="-pl='$PROJECTS -am'"
            --detect.parallel.processors=0
            --detect.project.name="${{ github.repository }}"
            --detect.project.version.name="${{ fromJson(steps.pull_request_ref.outputs.data).head.ref }}"
