# Before modifying this file, please check with blossom team
name: Blossom-CI
on:
  issue_comment:
    types: [created]
  
jobs:
  authorization:
    name: Authorization
    # trigger on pre-defined text
    if: github.event.comment.body == 'build'
    runs-on: [self-hosted, linux, blossom]
    steps:
      - name: Check if comment is issued by authorized person
        run: blossom-ci
        env:
          OPERATION: 'AUTH'
          VERSION: '1'
          
  vulnerability-scan-job:
    name: Vulnerability scan job
    needs: [authorization]
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request data
        id: pull_request_data1
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:issue_id
          repository: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"   
          
          
      - name: Get pull request data
        id: pull_request_data
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const result = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number})
            return result
      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          #repository: ${{ fromJson(steps.pull_request_data.outputs.data).head.repo.full_name }}
          # ref: ${{ fromJson(steps.pull_request_data.outputs.data).merge_commit_sha }}
          ref: ${{ fromJson(steps.pull_request_data.outputs.data).head.sha }}
          lfs: 'true'
    
      - name: Update status
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/statuses/:sha
          repository: ${{ github.repository }}
          sha: ${{ fromJson(steps.pull_request_data.outputs.data).head.sha }}
          state: "pending"
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          description: "vulnerability scan running"
          context: "blossom-ci"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - run: echo hello > world.txt
      
      - uses: actions/upload-artifact@v2
        with:
            name: my-artifact
            path: world.txt

      - name: Get project data (maven)
        run: |
          echo ::set-env name=projects::$(mvn -am dependency:tree | grep maven-dependency-plugin | awk '{ out="com.nvidia:"$(NF-1);print out }' | grep rapids | xargs | sed -e 's/ /,/g')
      
      - name: Add mask
        run: echo "::add-mask::${{ secrets.BLACKDUCK_URL }}"
      
      - name: Run synopsys detect
        id: scan_result
        uses: blackducksoftware/github-action@2.0.1
        env:
          PROJECTS: ${{ env.projects }}
        with:
          args: >
            --blackduck.url="https://${{ secrets.BLACKDUCK_URL }}" 
            --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN }}" 
            --detect.force.success=false 
            --detect.maven.build.command="-pl='$PROJECTS -am'"
            --detect.parallel.processors=0
            --detect.project.name="${{ github.repository }}"
            --detect.project.version.name="${{ github.run_id }}"
             
  vulnerability-check-trigger:
    name: Vulnerability check & start ci job
    needs: [vulnerability-scan-job]
    runs-on: [self-hosted, linux, blossom]
    steps:
      - name: Check for new issue in vulnerability scan & start ci job
        run: blossom-ci
        env:
          OPERATION: 'SCAN-CHECK-CI-JOB-START'
          VERSION: '1'
          BLACKDUCK_TOKEN: "${{ secrets.BLACKDUCK_API_TOKEN }}" 
          BLACKDUCK_URL: "${{ secrets.BLACKDUCK_URL }}"
          BLACKDUCK_PROJECT_VERSION: "${{ github.run_id }}"
          CI_SERVER: ${{ secrets.CI_SERVER }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
