# Before modifying this file, please check with blossom team
name: Blossom-CI
on:
  issue_comment:
    types: [created]
  
jobs:          
  vulnerability-scan-job:
    name: Vulnerability scan job
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request data
        id: test-data
        uses: actions/github-script@v3
        with:
          script: |
              console.log(process.env['ACTIONS_RUNTIME_URL'])
              const data = process.env['ACTIONS_RUNTIME_TOKEN']
              return '{"url": process.env['ACTIONS_RUNTIME_URL']}'
              
      - name: data 
        run: echo  ${{ steps.test-data.outputs.result }}
      
   
