# Before modifying this file, please check with blossom team
name: Blossom-CI
on:
  issue_comment:
    types: [created]
  
jobs:
  test:
    name: ravi
    runs-on: ubuntu-latest
    steps:
      - name: Get env variable
        id: actions-runtime-url
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
              return process.env['ACTIONS_RUNTIME_URL']
              
      - name: Get env variable
        id: actions-runtime-token
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
              return process.env['ACTIONS_RUNTIME_TOKEN']
        
  start-ci-job:    
    name: Start ci job
    runs-on: [self-hosted, linux, blossom]
    steps:
      - name: Get pull request data
        id: test-data
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
              return process.env['ACTIONS_RUNTIME_TOKEN']
      - name: Start ci job
        run: blossom-ci
        env:
          OPERATION: 'SCAN-CHECK-CI-JOB-START'
          VERSION: '1'
          BLACKDUCK_TOKEN: "${{ secrets.BLACKDUCK_API_TOKEN }}" 
          BLACKDUCK_URL: "${{ secrets.BLACKDUCK_URL }}"
          BLACKDUCK_PROJECT_VERSION: "${{ github.run_id }}"
          CI_SERVER: ${{ secrets.CI_SERVER }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUNTIME_URL: ${{ steps.actions-runtime-url.outputs.result }}
          RUNTIME_TOKEN: ${{ steps.actions-runtime-token.outputs.result }}
   
