# Make sure only few people can modify this file.
name: blossom-ci
on:
  issue_comment:
    types: [created]
  
jobs:          
  authorization:
    # trigger on pre-defined text
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/blossom-test'
    steps:
      - name: Check if comment writer is authorized person
        id: foo
        uses: ravitestgit/blossom-ci@master
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }} 
        shell: bash
