# Make sure only few people can modify this file.
name: blossom-ci
on:
  issue_comment:
    types: [created]
  
jobs:
  authorization:
    # trigger on pre-defined text
    if: github.event.comment.body == '/blossom-ci'
    runs-on: [self-hosted, linux, blossom]
    steps:
      - name: Check if comment writer is authorized person
        run: blossom-ci
        env:
          OPERATION: 'AUTH'
 
  vulnerability-scan-job:
    needs: [authorization]
    runs-on: ubuntu-latest
    steps:
      - run: prinenv
      - name: Get pull request ref
        id: pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:issue_id
          repository: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ fromJson(steps.pull_request_ref.outputs.data).head.ref }}
          lfs: 'true'

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Get project data (maven)
        run: |
          echo ::set-env name=projects::$(mvn -am dependency:tree | grep maven-dependency-plugin | awk '{ out="com.nvidia:"$(NF-1);print out }' | grep rapids | xargs | sed -e 's/ /,/g')
      
      - name: Add mask
        run: echo "::add-mask::nvidia.app.blackduck.com"
      
      - name: Run synopsys detect
        uses: blackducksoftware/github-action@2.0.1
        env:
          PROJECTS: ${{ env.projects }}
        with:
          args: >
            --blackduck.url="${{ secrets.BLACKDUCK_URL }}" 
            --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN }}" 
            --detect.force.success=false 
            --detect.maven.build.command="-pl='$PROJECTS -am'"
            --detect.parallel.processors=0
            --detect.project.name="${{ github.repository }}"
            --detect.project.version.name="${{ fromJson(steps.pull_request_ref.outputs.data).head.ref }}"
