# Make sure only few people can modify this file.
name: blossom-ci
on:
  issue_comment:
    types: [created]
  
jobs:          
  blossom-ci:
    # trigger on pre-defined text
    runs-on: [self-hosted, linux, blossom]
    if: github.event.comment.body == '/blossom-test'
    steps:
      - name: Run blossom ci
        run: blossom-ci
