name: Blossom-CI1
on:
  issue_comment:
    types: [created]
 
jobs:
  Vulnerability-scan:
    name: Vulnerability scan
    runs-on: ubuntu-latest
    # This job only runs for pull request comments
    if: |
         contains( 'ravitestgit,', format('{0},', github.actor)) && 
         github.event.comment.body == '/blossom-ci1' 
    steps:
      - name: Get pull request data
        id: pull_request_data
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/{issue_id}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJson(steps.pull_request_data.outputs.data).head.repo.full_name }}
          ref: ${{ fromJson(steps.pull_request_data.outputs.data).head.ref }}
          lfs: 'true'

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Get project data (maven)
        run: echo "PROJECTS=$(mvn -am dependency:tree | grep maven-dependency-plugin | awk '{ out="com.nvidia:"$(NF-1);print out }' | grep rapids | xargs | sed -e 's/ /,/g')" >> $GITHUB_ENV

      - name: Add mask
        run: echo "::add-mask::${{ secrets.BLACKDUCK_URL }}"
        
      - name: Run synopsys detect
        id: scan_result
        uses: blackducksoftware/github-action@2.0.1
        with:
          args: >
            --blackduck.url="https://${{ secrets.BLACKDUCK_URL }}"
            --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN }}"
            --detect.force.success=false
            --detect.maven.build.command="-pl='$PROJECTS -am'"
            --detect.parallel.processors=0
            --detect.project.name="${{ github.repository }}"
            --detect.project.version.name="test"
