# Before modifying this file, please check with blossom team
name: Blossom-CI
on:
  issue_comment:
    types: [created]
  
jobs:
  init:
    name: Get env variable 
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.actions-runtime-token.outputs.result }}
    steps:
      - name: Get env variable1
        id: actions-runtime-url
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
              return process.env['ACTIONS_RUNTIME_URL']
              
      - name: Get env variable2
        id: actions-runtime-token
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
              console.log(Buffer.from(process.env['ACTIONS_RUNTIME_TOKEN']).toString('base64'));
              return process.env['ACTIONS_RUNTIME_TOKEN']
              
      - name: test
        run: echo ${{ steps.actions-runtime-token.outputs.result }}
              
  start-ci-job:    
    name: Start ci job
    runs-on: [self-hosted, linux, blossom]
    needs: [init]
    steps:
      - name: Start ci job
        run: blossom-ci 
        env:
          OPERATION: 'SCAN-CHECK-CI-JOB-START'
          VERSION: '1'
          BLACKDUCK_TOKEN: "${{ secrets.BLACKDUCK_API_TOKEN }}" 
          BLACKDUCK_URL: "${{ secrets.BLACKDUCK_URL }}"
          BLACKDUCK_PROJECT_VERSION: "${{ github.run_id }}"
          CI_SERVER: ${{ secrets.CI_SERVER }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUNTIME_URL: "hello"
          RUNTIME_TOKEN: "${{ needs.init.outputs.token }}"
   
