# Copyright (c) 2020, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# A workflow to trigger ci on hybrid infra (github + self hosted runner)
name: Blossom-CI
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
      inputs:
          platform:
            description: 'runs-on argument'     
            required: true
          pull-request:
            description: 'pull request number'
            required: true
          code-checkout:
            description: 'code checkout required ?'     
            required: false
            default: 'false'
          code-checkout-repo:
            description: 'repo name for code checkout if code-checkout is set true'
            required: false
          code-checkout-ref:
            description: 'ref for code checkout like branch, sha if code-checkout is set true'
            required: false
          extra-args:
            description: 'extra argument'
            required: false
            
jobs:
  Authorization:
    name: Authorization
    outputs:
      output1: ${{ my_var }}
    # triggered on pre-defined text
    if: github.event.comment.body == 'build2' && contains( '["ravitestgit"]', github.actor )
    runs-on: blossom   
    steps:
      - name: Authorization
        run: blossom-ci
        env:
          REPO_TOKEN1: "${{ secrets.CI_TOKEN }}"
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPERATION: 'INIT'
  job2:
    runs-on: ubuntu-latest
    needs: Authorization
    steps:
    - run: echo ${{needs.Authorization.outputs.output1}}
        
  Work:
    name: Work PR# ${{ github.event.inputs.pull-request }}
    # triggered manually
    if: github.event_name == 'workflow_dispatch'
    runs-on: ${{ github.event.inputs.platform }}
    steps:
      - name: Run on self hosted runner
        if: github.event.inputs.platform == 'blossom'
        run: blossom-ci        
        env:
          REPO_TOKEN: "${{ secrets.CI_TOKEN }}"
          OPERATION: 'WORK'
          
      - name: Checkout code
        if: github.event.inputs.code-checkout == 'true'
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.code-checkout-repo }}
          ref: ${{ github.event.inputs.code-checkout-ref }}
          lfs: 'true'
          
      - name: Run on github hosted runner
        if: github.event.inputs.platform != 'blossom'
        uses: ravitestgit/blossom-action@main
