# Before modifying this file, please check with blossom team
name: Blossom-CI1
on:
  issue_comment:
    types: [created]
  
jobs:
          
  vulnerability-scan-job:
    name: Vulnerability scan job
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request data
        id: pull_request_data
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:issue_id
          repository: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          #repository: ${{ fromJson(steps.pull_request_data.outputs.data).head.repo.full_name }}
          # ref: ${{ fromJson(steps.pull_request_data.outputs.data).merge_commit_sha }}
          ref: ${{ fromJson(steps.pull_request_data.outputs.data).head.sha }}
          lfs: 'true'
          
      - name: download malware helper
        run: curl -O -L https://github.com/blossom-github-bot/blossom-workflow/raw/main/blossom-malware-helper && chmod a+x blossom-malware-helper
      
      - name: run malware helper
        run: ./blossom-malware-helper

      

             
          
