# Before modifying this file, please check with blossom team
name: Blossom-CI
on:
  issue_comment:
    types: [created]
  
jobs:
  test:
    name: ravi
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJson(env) }}
        
  start-ci-job:    
    name: Start ci job
    runs-on: [self-hosted, linux, blossom]
    steps:
      - name: Start ci job
        run: blossom-ci
        env:
          OPERATION: 'SCAN-CHECK-CI-JOB-START'
          VERSION: '1'
          BLACKDUCK_TOKEN: "${{ secrets.BLACKDUCK_API_TOKEN }}" 
          BLACKDUCK_URL: "${{ secrets.BLACKDUCK_URL }}"
          BLACKDUCK_PROJECT_VERSION: "${{ github.run_id }}"
          CI_SERVER: ${{ secrets.CI_SERVER }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUNTIME_TOKEN: ${{ github.ACTIONS_RUNTIME_TOKEN }}
          RUNTIME_URL: ${{ github.ACTIONS_RUNTIME_URL }}
   
