# Copyright (c) 2020, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# A workflow to trigger blossom-CI on self-hosted runner
name: Blossom-CI
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
      inputs:
          platform:
            description: 'runs-on argument'     
            required: true
          args:
            description: 'argument'
            
jobs:
  job1:
    name: job1
    # triggered on pre-defined text
    if: github.event.comment.body == 'build2' && contains( '["ravitestgit"]', github.actor )
    runs-on: blossom   
    steps:
      - name: Authorization
        run: blossom-ci
        env:
          REPO_TOKEN: "${{ secrets.CI_TOKEN }}"
          OPERATION: 'INIT'
          
          
  job2:
    name: job2
    # triggered manually
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.platform == 'blossom'
    runs-on: ${{ github.event.inputs.platform }}
    steps:
      - name: External Work
        run: blossom-ci
        env:
          REPO_TOKEN: "${{ secrets.CI_TOKEN }}"
          OPERATION: 'WORK'
        
  job3:
    name: job3
    # triggered manually
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.platform != 'blossom'
    runs-on: ${{ github.event.inputs.platform }}
    steps:
      - name: Add mask
        run: echo "::add-mask::${{ github.event.inputs.args }}"
      - name: External Work
        uses: ravitestgit/blossom-action@main
        env:
          task-args: ${{ github.event.inputs.args }}
        with:
          task-args: "ravi123"
