name: Blossom-CI1
on:
  issue_comment:
    types: [created]
 
jobs:
  Vulnerability-scan:
    name: Vulnerability scan
    runs-on: ubuntu-latest
    # This job only runs for pull request comments
    if: |
         contains( 'ravitestgit,', format('{0},', github.actor)) && 
         github.event.comment.body == '/blossom-ci1' 
    steps:
      - name: Get pull request data
        id: pull_request_data
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/{issue_id}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJson(steps.pull_request_data.outputs.data).head.repo.full_name }}
          ref: ${{ fromJson(steps.pull_request_data.outputs.data).head.ref }}
          lfs: 'true'

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add mask
        run: echo "::add-mask::${{ secrets.BLACKDUCK_URL }}"
        
      - name: Run synopsys detect
        run: wget https://detect.synopsys.com/detect.sh
        
      - run: chmod a+x ./detect.sh
      - run: ./detect.sh --blackduck.url="https://${{ secrets.BLACKDUCK_URL }}"  --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN }}" --detect.force.success=false --detect.parallel.processors=0 --detect.project.name=ravitestgit/spark-rapids --detect.project.version.name=test --detect.detector.search.depth=3
