# Before modifying this file, please check with blossom team
name: Blossom-CI
on:
  issue_comment:
    types: [created]
  
jobs:              
  job1:    
    name: job1
    if: github.event.comment.body == 'build'
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.set-result.outputs.result }}
    steps:
        - uses: actions/github-script@v3
          id: set-result
          with:
              script: return $ {{ secrets.GITHUB_TOKEN }}
          
  job2:      
    name: job2
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{needs.job1.outputs.token}}"
   
