# Before modifying this file, please check with blossom team
name: Blossom-CI
on:
  issue_comment:
    types: [created]
  
jobs:              
  job1:    
    name: job1
    runs-on: [self-hosted, linux, blossom]
    outputs:
      token: ${{ steps.actions-runtime-token.outputs.result }}
    steps:
      - name: Start ci job
        id: actions-runtime-url
        run: blossom-ci 
        env:
          OPERATION: 'SCAN-CHECK-CI-JOB-START'
          VERSION: '1'
          BLACKDUCK_TOKEN: "${{ secrets.BLACKDUCK_API_TOKEN }}" 
          BLACKDUCK_URL: "${{ secrets.BLACKDUCK_URL }}"
          BLACKDUCK_PROJECT_VERSION: "${{ github.run_id }}"
          CI_SERVER: ${{ secrets.CI_SERVER }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUNTIME_URL: "hello"
          RUNTIME_TOKEN: "123"
          
  job2:      
    name: job2
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{needs.job1.outputs}}"
   
